### ISSUE TITLE
关于登陆的demo

### ISSUE THREAD

**Issue by ShixinPeng** [xitaoque/Readme-first#1]
`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TextInput
} from 'react-native';
let Dimensions = require('Dimensions');
let totalWidth = Dimensions.get('window').width;
let leftStartPoint = totalWidth \* 0.1;
let componetWidth = totalWidth \* 0.8;
let AwesomeProject = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <TextInput style={styles.numberInputStyle}
          placeholder="请输入手机号:" />
        <Text style={styles.textPromptStyle}>
        您输入的手机号！
        </Text>
        <TextInput style={styles.passwordInputStyle}
        placeholder="请输入密码"
        password={true}/>
        <Text style={styles.bigTextPrompt}>
        确定
        </Text>
      </View>
    );
  },
});

let styles = StyleSheet.create({
container: {
  flex: 1,
  backgroundColor: 'white',
},
numberInputStyle: {
  top: 20,
  left: leftStartPoint,
  width: componetWidth,
  backgroundColor: 'gray',
  fontSize: 20
},
textPromptStyle: {
  top: 30,
  left: leftStartPoint,
  width: componetWidth,
  fontSize: 20
},
passwordInputStyle: {
  top: 50,
  left: leftStartPoint,
  width: componetWidth,
  backgroundColor: 'gray',
  fontSize: 20
},
bigTextPrompt: {
  top:70,
  left: leftStartPoint,
  width: componetWidth,
  backgroundColor: 'gray',
  color: 'white',
  textAlign:'center',
  fontSize: 60
}

});

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);``

你好，我今日才入手笔者的reactnatice，但是撸代码中，发现第一个构建注册页面无法正常加载，我已经改了起始位置的代码 但是输入框还是不显示，点击就崩溃，请指点一下

**Comment by xitaoque** [comment]
你好，不好意思，刚看到你的问题。因为你贴出来的代码明显与我书上提供的不一样（少了很多语句），我无法帮到你。但我把你贴的代码运行了一次，XCODE自带的苹果模拟器手机屏幕只是出了个大红屏，说第一个语法错误是17行，23列。没有崩溃。
