### ISSUE TITLE
setState 可接受对象和函数

### ISSUE THREAD

**Issue by walfud** [xitaoque/Readme-first#14]
书中 p.42 页中, 说
```javascript
uatePW: function(inputedNum) {
   this.setState(() => {
      return {inputedNum};
   });
}
```
与
```javascript
uatePW: function(inputedNum) {
   this.setState({inputedNum});
}
```
等价. 但是我认为, 第一个是传入了一个回调函数而第二个传入的是一个对象. 参考[这里](https://facebook.github.io/react/docs/react-component.html#setstate). 那么下面说 `setState` 全都是异步操作也是不准确的. 
不知道我的理解是否正确?

**Comment by xitaoque** [comment]
想知道是不是异步操作很简单啊？这两种写法，你各自在调用setState前与调用setState后马上打印一下this.state.inputedNum的值就知道了啊。如果调用后，打印的值变成了新的值，就说明setState是同步执行了的。
但是，事实上是，两种写法，调用了setState后马上打印this.state.inputedNum的值，会发现它的值还是原来的值。也就是说，setState语句后的打印语句被执行时，setState还没有改变状态机变量的值。说明它是个异步操作。

**Comment by walfud** [comment]
其实这是两个问题， 第一个是： setState 传入对象和传入函数并非完全等价， 毕竟是函数的重载而不是同一个语法， 而原文说 ‘完全等价’ 并不准确。第二个问题是该函数是异步函数， 这一点你说的没错。
