### ISSUE TITLE
请问没有原书代码么？

### ISSUE THREAD

**Issue by XiaStrong** [xitaoque/Readme-first#2]

**Comment by xitaoque** [comment]
摘自本书前言：
笔者希望读者在阅读本书时，能在理解的基础上将例程代码输入到电脑中。输入的过程
是一个消化吸收的过程。输入完成后，运行代码，并且按照提示或者针对自己有疑虑的地方
进行修改，以便深入理解各个知识点。
正因为如此，本书前面章节中那些短小精悍的例程并没有附在一张光盘上，或者在网上
提供下载地址，而是需要读者自己手动输入进电脑。
