### ISSUE TITLE
5.5.1 导航栏自定义组件的实现

### ISSUE THREAD

**Issue by jufengliushao** [xitaoque/Readme-first#4]
undefined is not an object(evaluating 'this.props.naviBarStatus.map')
代码是按照您书上的敲的，不知道这个是什么原因。

**Comment by xitaoque** [comment]
从错误提示来看，是没有this.props.naviBarStatus这个属性。你看一下你的代码中，是否把这个属性传进了NaviBar 组件。可以在NaviBar组件的render函数中加一行在函数首，console.log(this.props.naviBarStatus);，把这个属性打出来。如果打出来还是undefined，看看这个属性传入的代码，是不是漏了什么地方。
