### ISSUE TITLE
请问一下，这个警告您那边有没有好的解决办法？google也没能找到一个解决办法。

### ISSUE THREAD

**Issue by BrickWorkerKing** [xitaoque/Readme-first#5]
ExceptionsManager.js:78 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component.

**Comment by xitaoque** [comment]
这个异常我们在开发遇到过。产生这个异常的原因通常是上层组件提供属性有错误（没有提供），或者是组件使用上层组件提供的属性时使用错了（把一个类型当另一个类型使用）。仔细检查上层组件提供的属性，找到错误，就能解决这个问题。
