### ISSUE TITLE
https://github.com/xitaoque/1.3.2.3/tree/master怎么没有了？

### ISSUE THREAD

**Issue by ghost** [xitaoque/Readme-first#7]
https://github.com/xitaoque/1.3.2.3/tree/master怎么没有了？

**Comment by xitaoque** [comment]
你好，因为SublimeLinter这个插件升级后，对RN代码会报很多不是错误的错误，所以现在开发中不适合安装使用这个组件。所以这个分支被删除掉了。谢谢你的提醒，我一会儿把这个情况加入到Readme中去。
