### ISSUE TITLE
按书中代码2-3修改了JSX代码后出现红屏，请问该如何处理？

### ISSUE THREAD

**Issue by user19377331** [xitaoque/Readme-first#8]
按书中代码2-3节修改了JSX代码后出现红屏，请问该如何处理？我预览了下面的代码，提交后可能会有几行看不见，老师你在看的时候需要脑补上，非常感谢！
红屏信息如下：
SyntaxError /Users/Ray/Eating37/index.ios.js: Unexpected character'" (14:25)
RCTFatal + 104
-[RCTBatchedBridge stopLoadingWithError:] + 1138
__25-[RCTBatchedBridge start]_block_invoke_2 + 65
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_main_queue_callback_4CF + 1054
CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 9
__CFRunLoopRun + 2205
CFRunLoopRunSpecific + 420
GSEventRunModal + 161
UIApplicationMain + 159
main + 111
start + 1
0x0 + 1

修改后的代码如下：
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TextInput
} from 'react-native';
let Dimensions =require ('Dimensios')；
let totalWidth =Dimensions.get ('window').width;
let leftStartPoint = totalWidth*0.1;
let componentWidth = totalWidth*0.8;
let Eating37 = React.createClass({
render: function() {
    return (
      <View style={styles.container}>
        <TextInput style={styles.numberInputStyle}
            placeholder={'请输入手机号'}/>
        <Text style={styles.textPromptStyle}>
            请输入手机号：
        </Text>
        <TextInput style={styles.passwordInputStyle}
            placeholder={'请输入密码'}
            password={true}/>
        <Text style={styles.bigTextPrompt}>
          确定
        </Text>
      </View>
    );
  },
});
let styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  numberInputStyle:{
    top:20,
    left: leftstartpoint,
    width: componentwidth,
    backgroundColor: 'gray',
    fontSize:20
  },
  textpromptStyle:{
    top:30,
    left: leftstartpoint,
    width: componentwidth,
    fontSize:20
  },
  passwordInputStyle: {
    top:50,
    left: leftstartpoint,
    width: componentwidth,
    backgroundColor: 'gray',
    fontSize:20
  },
  bigTextPrompt: {
    top:70,
    left: leftstartpoint,
    width: componentwidth,
    backgroundColor: 'gray',
    fontSize:60
    textAlign: 'center',
    color: 'white',
  },
});

AppRegistry.registerComponent('Eating37', () => Eating37);

**Comment by xitaoque** [comment]
你好，你复制的代码可能问题比较多，比如有一个全角的分号，然后算宽高时少了两个星号。当我把这三个错误修改了后，报出下一个错误在第20行了。而你给出的错误信息显示代码错误在第14行，第25列。（SyntaxError /Users/Ray/Eating37/index.ios.js: Unexpected character'" (14:25)），因此只能请你按错误信息中提示的行号与列号自己再好好找一找了。

**Comment by user19377331** [comment]
根据您的提示，我又重新检查了一次代码，果然获得了很大的提高，非常感谢！不过仍然还有一些问题，我把代码用图片的方式上传了，这样就不会出现偏差了。以下是代码和错误信息：
![1](https://cloud.githubusercontent.com/assets/24453174/21053281/ad5dd4a2-be63-11e6-97e0-3a64476018fe.png)
![2](https://cloud.githubusercontent.com/assets/24453174/21053278/acd3c1c2-be63-11e6-9c66-101c6912bb90.png)
![4](https://cloud.githubusercontent.com/assets/24453174/21053279/ad5a8ec8-be63-11e6-99bc-721f573c672b.png)

**Comment by xitaoque** [comment]
错误信息用英文说的很明白了，你如果有什么单词不认识，百度翻译一下啊。它说的是找不到变量leftstartpoint啊。在代码头部定义这个变量时，定义的是leftStartPoint，S与P是大写，你下面全用小写了，所以说找不到这个变量啊。
你再看红屏的第三行，写着index.ios.js：45，就是说index.ios.js第45行发生了这个错误。

**Comment by user19377331** [comment]
非常感谢老师的建议，我已经调试成功！
