### ISSUE TITLE
红屏警告信息处理

### ISSUE THREAD

**Issue by user19377331** [xitaoque/Readme-first#9]
阙老师，我买了两本书，我觉得您写的书绝对是一流的好，每一个字我都用心在看。在后续的学习过程中我相信还会碰到很多红屏警告信息的问题，您是否能介绍一些有关错误信息解释及处理方法的相关书籍给我们呢？这样我就可以更好地自学了。

**Comment by xitaoque** [comment]
没有错误信息解释与处理方法的书籍，多碰到几次就有经验了。错误发生后，在红屏与日志输出界面通常都有错误的原因与发生的位置。英文的，仔细读读，不懂的单词百度翻译一下。就没什么了。输入时一定要注意别输入错误，象style输入成styles或者sytle，还有source输入成soruce都是容易犯的错误，并且不仔细还查不出来。
